"""add_realized_pnl

Revision ID: 2c279c9ecea7
Revises: 951ce9c3d36b
Create Date: 2026-01-08 15:29:17.609627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c279c9ecea7'
down_revision: Union[str, Sequence[str], None] = '951ce9c3d36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('trades', sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'realized_pnl')
    op.drop_column('portfolios', 'realized_pnl')
    # ### end Alembic commands ###
